apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase-validator
  labels:
    app: hbase-validator
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbase-validator
  template:
    metadata:
      labels:
        app: hbase-validator
    spec:
      containers:
      - name: hbase-validator
        image: your-registry/hbase-validator:latest
        ports:
        - containerPort: 8501
          protocol: TCP
        env:
        - name: STREAMLIT_SERVER_PORT
          value: "8501"
        - name: STREAMLIT_SERVER_ADDRESS
          value: "0.0.0.0"
        - name: STREAMLIT_SERVER_HEADLESS
          value: "true"
        - name: STREAMLIT_SERVER_ENABLE_CORS
          value: "false"
        - name: STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION
          value: "false"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /_stcore/health
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: config
          mountPath: /app/config.yaml
          subPath: config.yaml
          readOnly: true
        - name: reports
          mountPath: /app/reports
      volumes:
      - name: config
        configMap:
          name: hbase-validator-config
      - name: reports
        persistentVolumeClaim:
          claimName: hbase-validator-reports
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: hbase-validator-service
  labels:
    app: hbase-validator
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: http
  selector:
    app: hbase-validator

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hbase-validator-config
data:
  config.yaml: |
    # HBase数据迁移验证系统配置文件

    # 源端HBase配置
    source:
      host: "your-source-hbase-host"
      port: 9090
      table_name: "hope_saas_oms:oms_order_info"
      timeout: 30000

    # 目标端HBase配置  
    target:
      host: "your-target-hbase-host"
      port: 9090
      table_name: "hope_saas_oms:oms_order_info"
      timeout: 30000

    # 验证配置
    validation:
      max_rows: 1000
      max_workers: 10
      batch_size: 100
      timeout: 300
      verbose: true
      sample_rate: 1.0

    # 报告配置
    report:
      output_dir: "./reports"
      formats: ["json", "excel"]
      include_details: true
      max_detail_records: 1000

    # 日志配置
    logging:
      level: "INFO"
      file: "hbase_validation.log"
      format: "%(asctime)s - %(levelname)s - %(message)s"
      
    # Streamlit界面配置
    ui:
      title: "HBase数据迁移验证系统"
      default_display_rows: 100
      refresh_interval: 5

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hbase-validator-reports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: 根据腾讯云环境选择合适的存储类
